services:
  spts-test:
    image: yashwick/spts-test:latest #         # built via: docker build -f Dockerfile.test -t spts-test .
    container_name: spts-test-container
    ports:
      - "8000:8000"
    volumes:
      - ./sessions:/app/sessions
    env_file:
      - .env
    restart: unless-stopped
