import sqlglot
from sqlglot import exp

class SecurityViolationError(Exception):
    """Custom exception raised when destructive SQL is detected."""
    pass

def sanitize_sql(sql_query: str) -> str:
    """
    SEC-02: AST Query Sanitizer
    Parses the LLM-generated SQL and strictly enforces read-only (SELECT) operations.
    Blocks DROP, DELETE, UPDATE, INSERT, ALTER, and stacked queries.
    
    Args:
        sql_query (str): The raw SQL string generated by the LLM.
        
    Returns:
        str: The cleanly formatted, safe SQL query.
        
    Raises:
        SecurityViolationError: If DML/DDL commands or malformed queries are detected.
    """
    if not sql_query or not sql_query.strip():
        raise SecurityViolationError("Empty SQL query provided.")

    try:
        # Parse the query into a list of AST expressions.
        # This automatically handles and separates stacked queries (e.g., query1; query2;)
        statements = sqlglot.parse(sql_query, read="sqlite")
    except sqlglot.errors.ParseError as e:
        raise SecurityViolationError(f"SQL Parsing Error (Malformed Query): {str(e)}")

    if not statements:
         raise SecurityViolationError("No valid SQL statements found.")

    # Block stacked queries (e.g., "SELECT * FROM users; DROP TABLE users")
    if len(statements) > 1:
        raise SecurityViolationError("Stacked multiple queries are strictly prohibited.")

    ast = statements[0]

    # Ensure the root of the AST is explicitly a SELECT statement
    if not isinstance(ast, exp.Select):
        raise SecurityViolationError("Only SELECT statements are permitted. DML/DDL commands blocked.")

    # Deep check: Traverse the AST to ensure no destructive operations are hidden inside CTEs or subqueries
    forbidden_nodes = (exp.Delete, exp.Drop, exp.Update, exp.Insert, exp.AlterTable)
    for node in ast.find_all(forbidden_nodes):
        raise SecurityViolationError(f"Destructive operation ({node.key.upper()}) found within the query structure.")

    # Return the normalized, strictly safe SQL string
    return ast.sql(dialect="sqlite")

# --- Quick Local Test Block ---
if __name__ == "__main__":
    test_queries = [
        "SELECT name FROM schools WHERE API_Score > 800",
        "SELECT * FROM schools; DROP TABLE users;",
        "DELETE FROM schools WHERE API_Score < 500"
    ]
    
    for q in test_queries:
        print(f"\nTesting: {q}")
        try:
            safe_query = sanitize_sql(q)
            print(f"✅ Safe! Sanitized Output: {safe_query}")
        except SecurityViolationError as e:
            print(f"🚫 BLOCKED: {e}")