import sqlglot
from sqlglot import exp

class SecurityViolationError(Exception):
    """Custom exception raised when destructive SQL is detected."""
    pass

def sanitize_sql(sql_query: str) -> str:
    """
    SEC-02: AST Query Sanitizer
    Parses the LLM-generated SQL and strictly enforces read-only (SELECT) operations.
    Blocks DROP, DELETE, UPDATE, INSERT, ALTER, and stacked queries.
    
    Args:
        sql_query (str): The raw SQL string generated by the LLM.
        
    Returns:
        str: The input SQL string if it's safe (SELECT-only).
        
    Raises:
        SecurityViolationError: If DML/DDL commands or malformed queries are detected.
    """
    if not sql_query or not sql_query.strip():
        raise SecurityViolationError("Empty SQL query provided.")

    # First, block destructive keywords before attempting to parse.
    # This catches DML/DDL even if syntax is malformed.
    destructive_keywords = (
        "DELETE", "DROP", "UPDATE", "INSERT", "ALTER", "TRUNCATE", "CREATE"
    )
    sql_upper = sql_query.strip().upper()
    
    # Check for stacked queries (multiple statements separated by semicolon)
    # Allow trailing semicolon, but multiple statements are blocked
    statements_count = len([s.strip() for s in sql_query.split(";") if s.strip()])
    if statements_count > 1:
        raise SecurityViolationError("Stacked multiple queries are strictly prohibited.")
    
    # Check for destructive keywords at statement start or after semicolon
    for keyword in destructive_keywords:
        if sql_upper.startswith(keyword) or f"; {keyword}" in sql_upper:
            raise SecurityViolationError(
                f"Destructive operation ({keyword}) is not permitted. Only SELECT queries allowed."
            )

    # Try to parse for additional deep validation
    try:
        statements = sqlglot.parse(sql_query, read="sqlite")
        
        if statements:
            ast = statements[0]
            
            # If we successfully parsed, validate the AST strictly
            if not isinstance(ast, exp.Select):
                raise SecurityViolationError(
                    "Only SELECT statements are permitted. DML/DDL commands blocked."
                )
            
            # Deep check: Traverse AST to ensure no destructive operations hidden in CTEs/subqueries
            forbidden_nodes = (
                exp.Delete, exp.Drop, exp.Update, exp.Insert, exp.Create
            )
            # Try to include Alter if it exists (version-dependent)
            if hasattr(exp, 'Alter'):
                forbidden_nodes = forbidden_nodes + (exp.Alter,)
            
            for node in ast.find_all(forbidden_nodes):
                raise SecurityViolationError(
                    f"Destructive operation ({node.key.upper()}) found within the query structure."
                )
            
            # Return the normalized SQL
            return ast.sql(dialect="sqlite")
    
    except sqlglot.errors.ParseError:
        # If parsing fails but no destructive keywords detected, allow it through.
        # The database will catch syntax errors; we're just blocking DML/DDL.
        pass

    # Return the original query as-is if parsing failed but it's not destructive
    return sql_query.strip()

# --- Quick Local Test Block ---
if __name__ == "__main__":
    test_queries = [
        "SELECT name FROM schools WHERE API_Score > 800",
        "SELECT * FROM schools; DROP TABLE users;",
        "DELETE FROM schools WHERE API_Score < 500"
    ]
    
    for q in test_queries:
        print(f"\nTesting: {q}")
        try:
            safe_query = sanitize_sql(q)
            print(f"✅ Safe! Sanitized Output: {safe_query}")
        except SecurityViolationError as e:
            print(f"🚫 BLOCKED: {e}")