import sqlglot
from sqlglot import exp


DESTRUCTIVE_KEYWORDS = (
    "DELETE", "DROP", "UPDATE", "INSERT", "ALTER", "TRUNCATE", "CREATE",
    "ATTACH", "DETACH", "PRAGMA", "REINDEX", "VACUUM",
)

class SecurityViolationError(Exception):
    """Custom exception raised when destructive SQL is detected."""
    pass


def _count_statements(sql_query: str) -> int:
    return len([segment.strip() for segment in sql_query.split(";") if segment.strip()])


def _reject_obvious_destructive_sql(sql_query: str) -> None:
    sql_upper = sql_query.strip().upper()
    if _count_statements(sql_query) > 1:
        raise SecurityViolationError("Stacked multiple queries are strictly prohibited.")

    for keyword in DESTRUCTIVE_KEYWORDS:
        if sql_upper.startswith(keyword) or f"; {keyword}" in sql_upper:
            raise SecurityViolationError(
                f"Destructive operation ({keyword}) is not permitted. Only SELECT queries allowed."
            )


def _get_allowed_root(ast):
    if hasattr(exp, "With") and isinstance(ast, exp.With):
        return ast.this
    return ast


def _get_forbidden_nodes() -> tuple[type, ...]:
    node_names = [
        "Delete", "Drop", "Update", "Insert", "Create",
        "Command", "Transaction", "Merge", "AlterColumn", "Alter",
        "Attach", "Pragma",
    ]
    nodes = []
    for name in node_names:
        node = getattr(exp, name, None)
        if node is not None:
            nodes.append(node)
    return tuple(nodes)


def _validate_ast(statements) -> str:
    if not statements or len(statements) != 1:
        raise SecurityViolationError("Exactly one SQL statement is required.")

    root = _get_allowed_root(statements[0])
    allowed_roots = (exp.Select, exp.Union, exp.Except, exp.Intersect)
    if not isinstance(root, allowed_roots):
        raise SecurityViolationError("Only read-only SELECT queries are permitted.")

    forbidden_nodes = _get_forbidden_nodes()
    for node in statements[0].walk():
        if isinstance(node, forbidden_nodes):
            raise SecurityViolationError(
                f"Destructive or administrative operation ({node.key.upper()}) is not permitted."
            )

    return statements[0].sql(dialect="sqlite")

def sanitize_sql(sql_query: str) -> str:
    """
    SEC-02: AST Query Sanitizer
    Parses the LLM-generated SQL and strictly enforces read-only (SELECT) operations.
    Blocks DROP, DELETE, UPDATE, INSERT, ALTER, and stacked queries.
    
    Args:
        sql_query (str): The raw SQL string generated by the LLM.
        
    Returns:
        str: The input SQL string if it's safe (SELECT-only).
        
    Raises:
        SecurityViolationError: If DML/DDL commands or malformed queries are detected.
    """
    if not sql_query or not sql_query.strip():
        raise SecurityViolationError("Empty SQL query provided.")

    _reject_obvious_destructive_sql(sql_query)

    try:
        statements = sqlglot.parse(sql_query, read="sqlite")
        return _validate_ast(statements)
    except sqlglot.errors.ParseError:
        raise SecurityViolationError("SQL could not be safely parsed. Only valid read-only SELECT queries are allowed.")

# --- Quick Local Test Block ---
if __name__ == "__main__":
    test_queries = [
        "SELECT name FROM schools WHERE API_Score > 800",
        "SELECT * FROM schools; DROP TABLE users;",
        "DELETE FROM schools WHERE API_Score < 500"
    ]
    
    for q in test_queries:
        print(f"\nTesting: {q}")
        try:
            safe_query = sanitize_sql(q)
            print(f"✅ Safe! Sanitized Output: {safe_query}")
        except SecurityViolationError as e:
            print(f"🚫 BLOCKED: {e}")